- coffeescripts/xwing.coffee
- sass/xwing-print.sass
- sass/xwing-screen.sass
Examples:
Fancy web view:
Fancy print view (from PDF):
> Add upgrade card text to fancy print view

- coffeescripts/xwing.coffee
- sass/xwing-print.sass
- sass/xwing-screen.sass
- sass/xwing.sass
- tests/test_view_as_text.coffee
Add secondary weapon range and damage in the fancy print view.  Re-works the alignment of the stat bar icons as well to use vertical-align: middle instead of fixed offsets.
Also includes unit tests for upgrade test and secondary weapon range and damage in the fancy print view.
Resolves #154.
> Secondary weapon range and damage in fancy print view

- coffeescripts/cards-es.coffee
A *ton* of changes. What I've done:
-Translated all the expansion packs. It was weird to be the only language to don't use the oficial published names.
-Changed the text on many, many cards to match the oficial translation (and the FAQ changes on the few cases where it could be applied).
-Added the translation for TIE Defender, Z-95 Headhunter and VT-49 Decimator, as they were the only "old" ships using the original English name instead the one they have in the Spanish game.
-Translated all the new Scum and Villany ships, pilots and upgrades, including the faction name (Escoria y Villanos).
-Added the generic pilots for M3-A Interceptor*, StarViper and Scum Z-95.
-Moved Dace Bonearm from Y-Wing to its HWK-290. Added the missing Hired Gun on his place.
-Added the translation for a few …
> Updated cards-es.coffee

- coffeescripts/cards-es.coffee
Some extra things I've seen after the files were merged and uploaded:
-Mandalorian Mercenary (Scum Firespray) and Wild Space Fringer (YT-2400) weren't translated due no entry on the file.
-Black Sun Enforcer was missing in the builder due the StarViper name change, as he didn't had a ship assigned.
-Airen Cracken had the same problem due the Z-95 name change.
-Patrol Leader (Decimator) was missing due the ship name change, but he also didn't have an entry on the file.
-R4 Agromech and R4-B11 had blank cards due no entry. Added both.
-IG-88B had a typo on his %CANNON%, showing the misspelled word instead the icon.
-Small typos in a few other lines.
And I think that is all. Except for the "SCUM ONLY" (on Greedo, i.e.) that I have no idea where it is. It should be "SOLO ESCORIA".
> extra changes on cards-es.coffee

- coffeescripts/cards-es.coffee
Translated the titles from issue #189 . 
I've also added Bomb Loadout (and its translation) to Upgrades, which wasn't showing up on the Spanish builder (on both Rebel and Scum Y-wings nor in any other ship with Torpedoes). I don't know if it will appear after this or you'll need to do something else. 
Maybe I should have opened a new Issue with this last thing, but I thought I could just use this Pull :p
I've also did a general recheck for more missing or problematic cards, but I've been unable to find anything. With a bit of luck this will be all until they release new things.
> Titles translated

- coffeescripts/cards-es.coffee
-Translated all the cards from the Imperial Raider expansion pack.
-Added several of them that were blank on the Card Browser (most of the Huge Ships Only crew).
-Added translations for the Wave 7 Expansion Packs and ships, as we already know what will be the official translation. Last time this broke something on another file causing a couple problems (no pilots on a certain ship, another without certain slots if I remember correctly), so you may want to check it. In any case, I will notify you of any issue after the merge. 
And that's it, I think :P
> Imperial Raider translation

- coffeescripts/cards-es.coffee
Translated all the cards included on the Hound's Tooth expansion to Spanish. I've also added those that weren't on the list so were showing blank on the builder. More precisely:
-Glitterstim
-Hound's title
-Trandoshan Slaver
-Bossk (the pilot)
Tomorrow I should have the Punisher cards, and maybe K-wing. Khiraxz, soon I hope.
> Hound's Tooth cards translation

- coffeescripts/cards-es.coffee
-Translated everything form the K-Wing expansion
-Added Advanced Slam as it was missing on the list (appeared blank)
-Fixed a typo on Palpatine card, and an error from the official translation which will be surely regarded in our regional FAQ. As it was published, Palpatine couldn't be used on any dice roll made by his ship.
I still haven't had the chance to get my hands on a Kihraxz to translate its part. Soon.
> K-wing translation

- coffeescripts/cards-es.coffee
-Translated the expansion name
-Added and translated Tech upgrade
-Added the translation for the T-70 and TIE/fo ships*
-Added the "ship: ###" tag to both, T-70 and TIE/fo pilots (including the single expansion packs) to avoid problems with the ship name change*
-Translated all the pilots, adding the non-unique missing ones
-Added the unspoiled pilots from the single expansions. They have no purpose right now, but this way there will be no chance for me to miss them once they are spoiled/published, while being more faithful to the original (english) version of the Builder.
-Translated the upgrade cards
*If I remember correctly, adding the translated ship name to each pilot should avoid the problems this could case (pilots disappearing from the builder and so). The first time I translated …
> Force Awaken Core Set translation

- coffeescripts/cards-en.coffee
- coffeescripts/cards-es.coffee
- coffeescripts/cards-fr.coffee
- coffeescripts/cards-pl.coffee
- coffeescripts/cards-ru.coffee
- coffeescripts/xwing.coffee
Added a button to the BBCode and HTML list modals, which first when clicked selects the contents of the textarea and then performs an exec('copy') command. If the copy command is not supported on the device, text should remain selected to ease manual copying.
Relates to issue #240
> #240: Copy to clipboard

- package.json
Update dependencies (`grunt-sass` in particular) which are causing a very outdated version of `node-sass` to install and fail the `libsass` binding post-install script.
See #241
> #241: Updating some of the package dependencies

- coffeescripts/xwing.coffee
Adds the squad name to the permalink as parameter 'sn'
Optionally (if notes are filled out), updates the permalink with the notes as parameter 'sno'.  This only happens on change of the textarea, instead of every keyup, as it seemed excessive otherwise.
> Permalink now includes name and (optionally) notes

- coffeescripts/cards-es.coffee
After some time away from X-wing, it's time to keep these translations up to date :P
-Added translated names for T-70, TIE/fo and Gozanti expansions
-Translated all the pilots and new cards from the expansions above
-Added 'ship' tag to both TIE Defender titles*
*Title slot is missing in TIE Defenders in Spanish. I can't remember if we needed to do something else besides adding the 'ship' tag with the translated name to fix it. If so, feel free to do it :P
> Translated TIE/fo, T-70 and Gozanti cards

- coffeescripts/cards-es.coffee
- jade/index.jade
**Cards-es.coffe:**
-Translated all the cards included in the Ghost expansion pack
-Translated all the names of the Wave 8 Expansion Packs.
-Added the Lothal Rebel pilot for the VCX (and it's translation) as it was missing.
-Added two TIE Bombers pilots from the future Veteran pack that weren't showing in the builder, including the 'ship' tag to secure the deal.
-Added the 'ship: TIE Bomber' tag in the TIE Shuttle title as the title slot was missing on them.
**index.jade**
-Took the liberty of adding myself in the Spanish credits. Not that I care of these things, but it was starting to feel weird even to me :P
And I think that's all. Rest of Wave 8 once I get my hands on them. It had a late release in Spain due holidays.
> Ghost cards and a few extra things

- coffeescripts/cards-es.coffee
-Translated Attack Shuttle name, as I missed it in the last update, and added 'ship' tags everywhere to avoid problems
-Translated all the cards from the other Wave 8 ships (G-1A, JumpMaster, TIE Prototype)
-Translated those three ships names and added the 'ship' tags to avoid problems.
-Added all the generic pilots of those three ships.
-Added 'ship' tag to Deathfire from Imperial Veterans as it was missing.
> Wave 8 completed

- coffeescripts/cards-es.coffee
-Translated all the cards from Wave 9 except the upgrades from TIE/sf and Shadowcaster. Hope to get them soon.
-Added Wave 9 Expansion Packs and ships translations
-Added the generic Protectorate Starfighter/Shadowcaster/TIE SF pilots
-Added "ship:" tags to all the Wave 9 pilots to avoid problems with the ship name translation
-Added "ship:" tags to the HotR T-70 pilots as they weren't showing up.
-Added "ship:" tags (and the two unspoiled pilots) for the Sabine TIE pilots, as they weren't showing up.
> Spanish Wave 9 and a couple fixes

- coffeescripts/cards-common.coffee
removed arc-170, sf tie, protectorate, and SC from unreleased expansions
> Wave 9 released

- coffeescripts/cards-es.coffee
-Translated all the Shadowcaster upgrade cards, and added the "ship" tag to the ShadowCaster title as the slot was missing.
-Fixed a typo on the "ship:" tag on the Protectorate Starfighter pilots ("Caza estelar...." when should be "Caza Estelar...".), as the pilots aren't showing up right now.
-Added "ship:" tag to the /sf and Sabine Masterpiece titles, as they were missing.
Now, the issue: ARC-170 has disappeared from the builder. Looking the file, it occurs to me that may be caused me adding it to the "renameship" list... something that seems I shouldn't have done due being the same name. I mean, yesterday I didn't realize that the few ships with the same name on both languages (both YT and the YV-666) aren't on the list. I guess this may be the cause of the Travis error from yesterday. …
> Shadowcaster upgrades, few extra fixes and a issue

- coffeescripts/cards-es.coffee
-Added "ship" tag to the Protectorate Starfighter title
-Deleted and added again the entire Gyroscopic Targeting, plus adding the "ship" tag for it. For some reason it wasn't showing in the Modification list but the builder was acknowledging its existence (i.e. adding it on the english version and then switching to spanish the translated Gyroscopic would be there, while if it was missing would just disappear). I didn't see any problem on the entry, hence the rewrite and the added tag. I hope it will work :(
> couple extra fixes

- coffeescripts/cards-es.coffee
-Added and translated the Expansion Packs and Ship names for Upsilon, Quadjumper and Sabine's TIE.
-Added and translated all the generic pilots for the Upsilon and Quadjumper.
-Translated all the new cards of the three expansions, adding the "ship" tag wherever it was needed due changing the ship's name.
-Translated Commander Kenkirk rank, something it was never done.
> Rest of Wave X

- coffeescripts/cards-en.coffee
Per the changes from this article: https://www.fantasyflightgames.com/en/news/2017/3/6/bringing-balance-to-the-force/
And from this document published by Fantasy Flight Games (FFG): https://images-cdn.fantasyflightgames.com/filer_public/06/c6/06c65609-ab37-4222-9d67-180efa490da6/x-wing_faq_v430.pdf
I have updated the text of the following cards:
- Manaroo
- Emperor Palpatine
- TIE/x7
- Zuckuss
Now they match the Errata found in the above articles.
> Updated English cards per FFG FAQ on 3/6/2017

- coffeescripts/cards-es.coffee
-Some typos in names I've been alerted of (and a name wrongly translated: Rebel Operator).
-Added 'ship' tags to Rebel HWK pilots because why not.
-Fixed the ship name on the 'ship' tag for Deathfire, causing him to be missing.
> minor fixes

- coffeescripts/cards-common.coffee
- coffeescripts/cards-de.coffee
- coffeescripts/cards-en.coffee
- coffeescripts/cards-es.coffee
- coffeescripts/cards-fr.coffee
- coffeescripts/cards-hu.coffee
- coffeescripts/cards-pl.coffee
- coffeescripts/cards-tr.coffee
> Fix: Wullfwarro -> Wullffwarro

- coffeescripts/cards-de.coffee
Add "TIE-Turbojäger" to upgrade cards
> #502 TIE advanced title is missing in German

- coffeescripts/cards-common.coffee
Per the XWS spec, pilots only need the release SKU suffix if they are in the same faction and ship (i.e. Han Solo, Poe Dameron, etc.)
> Removes -swx70 canonical_name suffix for dalan oberos in the m12-l

- coffeescripts/cards-en.coffee
> Fixes text for crossfire formation upgrade card

- coffeescripts/cards-es.coffee
This time I'll do it once per expansion, to minimize risks.
-Added Black Sun Assassin for the Starviper.
-Translated all the Saw's Expansion cards, while adding all the missing generic ships and corresponding tags.
-Added both Expansions translated names to the list, as well the TIE Reaper ship name.
> Second attempt for Wave 14 :P
