coffeescripts/cards-de.coffee
coffeescripts/cards-en.coffee
coffeescripts/cards-es.coffee
coffeescripts/cards-fr.coffee
coffeescripts/xwing.coffee
sass/xwing-print.sass
sass/xwing.sass

Moved all the black-and-white printing styles to a `.bw` class.  Defaults to black-and-white.
What do I do for translations?  Google translate?

Add color print checkbox

---

coffeescripts/cards-es.coffee

Translated all the TIE Punisher cards to Spanish, and added Extra Munitions as it was missing on the list.
Rest of Wave 7, soon™.

TIE Punisher translation

---

coffeescripts/cards-es.coffee

-Translated all the Kihraxz cards
-Translated Twin Ion Engine, as somehow I missed it when I did the Punisher.

Remaining Wave 7 translation

---

coffeescripts/cards-de.coffee

sorry, missing lines on the raider and I forgot Bossk

fixes on Wave 7 german translation

---

coffeescripts/cards-de.coffee

More fixes on Wave 7 and changes since FAQ 3.02

More fixes on Wave 7 and changes since FAQ 3.02

---

coffeescripts/cards-de.coffee

please also merge the 8777852 -> it is having the missing advanced SLAM

added german translation for "force awaken" set

---

coffeescripts/cards-common.coffee
coffeescripts/manifest.coffee
tests/test_expansions.coffee

T-70 X-Wing and TIE/fo Fighter are available.

Wave8 t70 fo

---

coffeescripts/cards-common.coffee
coffeescripts/manifest.coffee

Added the missing Gozanti maneuvers and pilot card.

add gozanti maneuvers and pilot card

---

coffeescripts/cards-de.coffee
coffeescripts/xwing.coffee

wrong name for Autocannon and fix for "Ordnance Tubes" so that it works also in Customs

fix for name and tubes

---

coffeescripts/cards-de.coffee

Added Glaive Squadron Pilot and Gamma Squadron Veteran, as thy were missing in the German version.

Imperial Veterans preview

---

coffeescripts/cards-es.coffee

-Added the Imperial Veterans expansion pack and its translation to the list.
-Translated all the cards included on it (Maarek was already translated).

Imperial Veterans

---

coffeescripts/cards-de.coffee
coffeescripts/cards-en.coffee
coffeescripts/cards-es.coffee
coffeescripts/cards-fr.coffee
coffeescripts/cards-pl.coffee
coffeescripts/cards-ru.coffee
coffeescripts/cards-tr.coffee

Also normalizes the Turkish translation (was missing a now-removed linebreak).
MERGE IT.  MERGE IT NAO.

Makes Adaptability way less annoying to print.

---

coffeescripts/cards-common.coffee

I don't think it makes any difference to the Squad Builder, but it does to my slack bot. :)

The YT-1300 is now Rebel and Resistance

---

coffeescripts/cards-es.coffee

-Added "ship:" tags to Ahsoka Tano and Captain Rex as there weren't appearing to the rebel TIE Fighter list in the spanish version.
-Translated all the new cards from Heroes of the Resistance but the YT-1300 pilots.

Heroes of the Resistance

---

coffeescripts/cards-es.coffee

This pilot wasn't showing in the YT-1300 list. I assume the reason was that lower case "t" typo in Yt-1300.

Resistance Sympathizer fix

---

coffeescripts/cards-es.coffee

It wasn't appearing in the mod lists for the rebel TIE. Added the 'ship' tag.

Captured TIE missing

---

coffeescripts/cards-es.coffee

-Added the translation of both expansion names.
-Added the translation of both ship names.
-Added and translated all the generic pilots of both expansions.
-Translated all the cards of both expansions, adding :ship: tags when needed to avoid problems.
EDIT: LOL at the ship emote.

U-Wing and TIE Striker

---

coffeescripts/cards-es.coffee

Seems I forgot a couple things:
-Added the ship tag to Adaptive Ailerons
-Translated Pivot Wing name.

couple fixes

---

coffeescripts/cards-de.coffee

Fix german translation of Han Solo (TFA)

Fix german

---

coffeescripts/cards-es.coffee

Updated the cards with the changes made to them due erratas and nerfs. 
This is something I used to do time ago, when I started translating this, but I stopped as the official Spanish version of the FAQs was usually released with a 8-10 months delay. But as the next Tatooine Open will use this builder as *the* builder, I thought I should update everything to avoid problems.

FAQs Spanish

---

coffeescripts/cards-es.coffee

-Added "ship" tag on it, as it wasn't appearing in the builder. 
I hope it will be the last of these small fixes for a while :P
EDIT: I shouldn't have said that. Some extra fixes added below XD

Light Scyk title missing

---

coffeescripts/cards-es.coffee

-Fixed a lowercase that caused the pilot to be missing.

 	Zealous Recruit fix

---

coffeescripts/xwing.coffee
tests/test_permalink.coffee

Uses HTML5's session history management to replace current URL with permalink.  Browser support is is 94.57% according to https://caniuse.com/#search=replaceState
All changed areas of code have been tested locally and found to be functioning the same as the deployed version.

Updates current URL every 250ms with latest permalink

---

coffeescripts/cards-de.coffee
coffeescripts/cards-es.coffee

-Fixed a typo in the Munitions Failsafe Spanish translation
-Fixed the Light Scyk title missing in the Deutsch translation that someone was claiming here: https://github.com/geordanr/xwing/pull/446#issuecomment-302379290
It won't appear translated, but at least it will appear :P

couple fixes 

---

coffeescripts/cards-es.coffee

Added the ship tags for both titles, Kihraxz and Viper, as they were missing.

Scum Aces titles

---

coffeescripts/cards-es.coffee

Added ship tag as it was missing. Someday I will have all these little things fixed, I promise :P

Viktor Hell fix

---

coffeescripts/cards-de.coffee
tests/test_rebel_aces.coffee
tests/test_translation_de.coffee

Bugfix TIE-Aggressor
renamed "Wing" to "Flügler"

bugfix #494 German Translation

---

coffeescripts/cards-de.coffee

DE missing FAQ at advanced SLAM

DE_descriptions

---

coffeescripts/cards-es.coffee

-Translated all the cards from the Scum Aces and Waves 12 and 13. 
-Added the usual generic pilots so they can be translated.
-Added 'ship' tags everywhere to avoid problems.

Guns for Hire, Wave 12, Wave 13

---

coffeescripts/cards-es.coffee

-Added the 'ship' tag on Blackout as it went missing.

'Blackout' fix

---

coffeescripts/cards-de.coffee

DE descriptions
